//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataMetric
    {
        public int id { get; set; }
        public string value { get; set; }
        public int idMetric { get; set; }
    
        public virtual Metric Metric { get; set; }
    }
}
namespace AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Device()
        {
            this.DeviceEmployees = new HashSet<DeviceEmployee>();
            this.HistoriqueCommandes = new HashSet<HistoriqueCommande>();
            this.Metrics = new HashSet<Metric>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string adressMac { get; set; }
        public Nullable<int> idTypeDevice { get; set; }
        public string description { get; set; }
        public Nullable<bool> disabled { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceEmployee> DeviceEmployees { get; set; }
        public virtual TypeDevice TypeDevice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriqueCommande> HistoriqueCommandes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Metric> Metrics { get; set; }
    }
}
namespace AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceEmployee
    {
        public int id { get; set; }
        public Nullable<int> idDevice { get; set; }
        public Nullable<int> idEmployee { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
namespace AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.DeviceEmployees = new HashSet<DeviceEmployee>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public Nullable<bool> isAdmin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceEmployee> DeviceEmployees { get; set; }
    }
}
namespace AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriqueCommande
    {
        public int id { get; set; }
        public string commandeName { get; set; }
        public Nullable<int> idDevice { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
    
        public virtual Device Device { get; set; }
    }
}
namespace AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Metric()
        {
            this.DataMetrics = new HashSet<DataMetric>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> nbrValues { get; set; }
        public Nullable<int> idDevice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DataMetric> DataMetrics { get; set; }
        public virtual Device Device { get; set; }
    }
}
namespace AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeDevice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeDevice()
        {
            this.Devices = new HashSet<Device>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Device> Devices { get; set; }
    }
}
