//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AtlantisWindowsEntities : DbContext
    {
        public AtlantisWindowsEntities()
            : base("name=AtlantisWindowsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataMetrics> DataMetrics { get; set; }
        public virtual DbSet<DeviceEmployees> DeviceEmployees { get; set; }
        public virtual DbSet<Devices> Devices { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Metrics> Metrics { get; set; }
        public virtual DbSet<TypeDevices> TypeDevices { get; set; }
        public virtual DbSet<HistoriqueCommandes> HistoriqueCommandes { get; set; }
    }
}
